config/routes.rb
Rails.application.routes.draw do
  root "games#index"
  get "games/ranking_manejo", to: "games#ranking_manejo"
  get "games/ranking_petroleo", to: "games#ranking_petroleo"
  resources :answers
  resources :questions
  resources :categories
  resources :games, only: [:index, :new, :create]
  resources :game_answers, only: [:new, :create]
  
  namespace :authentication, path: '', as:'' do
    resources :users
    resources :sessions, only: [:new, :create, :destroy]
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :category
  has_many :answers
  has_one_attached :image

  validates :question, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]
  before_action :set_categories, only: %i[ new create edit update ]
  before_action :set_time_alert, only: %i[ create update destroy]

  # GET /questions or /questions.json
  def index
    filtered = Question.where("question LIKE ?", "%#{params[:filter]}%")
    @pagy, @questions = pagy(filtered.all, items: 10)
    @filter = params[:filter]

    # Question.all.each do |question|
    #   question.answers.create(answer: "Se quedo sin tiempo", is_correct: false, active: false)
    # end
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to questions_url(@question), notice: "Pregunta agregaga." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to questions_url(@question), notice: "Pregunta actualizada." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    def set_categories
      @categories = Category.all
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:question, :score, :category_id, :image)
    end

    def set_time_alert
      @time_alert = '3'
    end

end

app/views/questions/_form.html.erb
<%= form_with(model: question) do |form| %>
  <div class="col-6 mt-2">
    <%= form.label :question, "Pregunta" %>
    <%= form.text_area :question, class:"form-control" %>
  </div>

  <div class="col-6 mt-2">
    <%= form.label :score, "Puntaje" %>
    <%= form.number_field :score, class:"form-control" %>
  </div>

  <div class="col-6 mt-2">
    <%= form.label :category_id, "Categoria" %>
    <select value="" class="form-control" id="question_category_id" name="question[category_id]" required>
      <% @categories.each do |category|%>
        <% if category.id == question.category_id %>
          <option value="<%= category.id %>" selected> <%= category.name %> </option>
        <%else %>
          <option value="<%= category.id %>"> <%= category.name %> </option>
        <%end%>
      <% end %>
    </select>
  </div>

  <% if question.image.attached? %>
    <div class="mt-2 mb-2 row">
      <div class="col-4">
        <%= image_tag( question.image , class: "rounded float-start d-block", size: "100X100", alt: "Question image") %>
      </div>
    </div>
  <% end %>

  <div class="form-group mt-2">
    <%= form.label :image, "Imagen" %>
    <%= form.file_field :image %>
  </div>

  <div class="mt-4">
    <%= form.submit "Guardar", class:"btn btn-primary" %>
    <%= link_to "Volver", questions_path, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<tr>
  <td> <%= question.question %> </td>
  <td> <%= question.score %> </td>
  <td> <%= question.category.name %> </td>
  <td> 
    <%= link_to inline_svg_tag('menu-alt2.svg', alt: 20, height: 20), answers_path(question_id: question.id), class: "btn btn-sm btn-outline-info", title: "Respuestas" %> 
    <%= link_to inline_svg_tag('pencil.svg', alt: 20, height: 20), edit_question_path(question), class: "btn btn-outline-warning btn-sm", title: "Editar" %>
  </td>
</tr>

app/views/questions/edit.html.erb
<h1>Editar pregunta</h1>

<%= render "form", question: @question %>

app/views/questions/index.html.erb
<h1>Preguntas</h1>
<%= link_to"<i class='fui-plus'></i> Nueva pregunta".html_safe, new_question_path, class: "btn btn-primary mt-2 mb-4" %>

<div class='row mb-2 col-4' id='form-questions-filter'>
    <%= form_with url: questions_path, method: :get, 
      data: { controller: "filter", action: "input->filter#submit", turbo_frame: "questions_table_body", turbo_action: "advance" } do %>
      <%= text_field_tag "filter", nil, placeholder: "Buscar...", class: "form-control", value: @filter, autofocus:true %>
    <% end %>
  </div>

<table class="table table-hover">
  <thead class="table-dark">
    <tr>
      <td>Pregunta</td>
      <td>Puntaje</td>
      <th>Categoria</th>
      <td>Acciones</td>
    </tr>
  </thead>
  <tbody id="questions_table_body">
    <%= turbo_frame_tag "questions" do%>
      <%= render @questions %>
    <%end%>
  </tbody>
</table>
<div class="pagination">
  <%== pagy_bootstrap_nav(@pagy, link_extra: 'data-turbo-action="advance"') %>
</div>

app/views/questions/new.html.erb
<h1>Nueva pregunta</h1>

<%= render "form", question: @question %>

app/views/questions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @question %>

<div>
  <%= link_to "Edit this question", edit_question_path(@question) %> |
  <%= link_to "Back to questions", questions_path %>

  <%= button_to "Destroy this question", @question, method: :delete %>
</div>