config/routes.rb
Rails.application.routes.draw do
  root "games#index"
  get "games/ranking_manejo", to: "games#ranking_manejo"
  get "games/ranking_petroleo", to: "games#ranking_petroleo"
  resources :answers
  resources :questions
  resources :categories
  resources :games, only: [:index, :new, :create]
  resources :game_answers, only: [:new, :create]
  
  namespace :authentication, path: '', as:'' do
    resources :users
    resources :sessions, only: [:new, :create, :destroy]
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :answer, presence: true

  scope :actives, -> { where(active: true) }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: %i[ show edit update destroy ]
  before_action :set_question, only: %i[ index new ]

  # GET /answers or /answers.json
  def index
    @answers = Answer.where(question_id: params[:question_id], active: true)
  end

  # GET /answers/1 or /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers or /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to answers_path(question_id: @answer.question_id), notice: "Respuesta agregada." }
        format.json { render :show, status: :created, location: @answer }
      else
        @question = Question.find(answer_params[:question_id])
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1 or /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to answer_url(@answer), notice: "Respuesta actualizada." }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1 or /answers/1.json
  def destroy
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url, notice: "La respueta fue eliminada." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    def set_question
      @question = Question.find(params[:question_id])
    end

    # Only allow a list of trusted parameters through.
    def answer_params
      params.require(:answer).permit(:answer, :is_correct, :question_id)
    end
end

app/views/answers/_answer.html.erb
<tr>
  <td> <%= answer.answer %> </td>
  
  <% if answer.is_correct? %>
    <td>Correcta</td>
  <%else%>
    <td>Incorrecta</span></td>
  <%end%>
  <td>
    <%= link_to "Editar", edit_answer_path(answer), class: "btn btn-warning" %>
  </td>
</tr>

app/views/answers/_form.html.erb
<%= form_with(model: answer) do |form| %>
  <% if answer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
        <% answer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :answer, "Respuesta"%>
    <%= form.text_field :answer,class:"form-control col-6" %>
  </div>

  <div>
    <%= form.label :is_correct, "Es correcta" %>
    <%= form.check_box :is_correct %>
  </div>

  <%= form.hidden_field :question_id, value: question_id %>

  <div class="mt-2">
    <%= form.submit "Guardar", class:"btn btn-primary" %>
    <%= link_to "Volver", answers_path(question_id: question_id ), class: "btn btn-danger" %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editar respuesta a la pregunta: </h1>
<h3> <%= @answer.question.question %> </h3>

<%= render partial:"form", locals: {answer: @answer,question_id: @answer.question_id } %>

app/views/answers/index.html.erb
<h1>Respuestas</h1>
<h3> <%= @question.question %></h3>
<%= link_to "<i class='fui-arrow-left'></i> Volver".html_safe, questions_path, class: "btn btn-info mt-2 mb-4 mr-4" %>
<%= link_to "<i class='fui-plus'></i> Agregar respueta".html_safe, new_answer_path(question_id: @question.id), class: "btn btn-primary mt-2 mb-4" %>
<table class="table">
  <thead class="table-dark">
    <tr>
      <td>Respuesta</td>
      <td>Es correcta</td>
      <td>Acciones</td>
    </tr>
  </thead>
  <tbody>
    <%= render @answers %>
  </tbody>
</table>

app/views/answers/new.html.erb
<h1>Agregar respuesta a la pregunta: </h1>
<h3> <%= @question.question %> </h3>

<%= render partial:"form", locals: {answer: @answer,question_id: @question.id } %>

app/views/answers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @answer %>

<div>
  <%= link_to "Edit this answer", edit_answer_path(@answer) %> |
  <%= link_to "Back to answers", answers_path %>

  <%= button_to "Destroy this answer", @answer, method: :delete %>
</div>