config/routes.rb
Rails.application.routes.draw do
  root "games#index"
  get "games/ranking_manejo", to: "games#ranking_manejo"
  get "games/ranking_petroleo", to: "games#ranking_petroleo"
  resources :answers
  resources :questions
  resources :categories
  resources :games, only: [:index, :new, :create]
  resources :game_answers, only: [:new, :create]
  
  namespace :authentication, path: '', as:'' do
    resources :users
    resources :sessions, only: [:new, :create, :destroy]
  end
end

app/views/layouts/_flash.html.erb
<div id="notice" data-controller="flash" class="col-6 mx-auto" 
  data-tiempo="<%= (time_alert.nil?) ? '2' : time_alert %>" 
  data-effect="<%= (effect_alert.nil?) ? 'rubberBand' : effect_alert %>">
  <% if notice.present? %>
    <div class="alert alert-primary alert-dismissible text-center" role="alert">
      <%= notice %>
    </div>
  <% end %>
  <% if alert.present? %>
    <div class="alert alert-danger alert-dismissible text-center" role="alert" >
      <%= alert %>
    </div>
  <% end %>
  <% if success.present? %>
    <div class="alert alert-success alert-dismissible text-center" role="alert" >
      <%= success %>
    </div>
  <% end %>
  <% if warning.present? %>
    <div class="alert alert-warning alert-dismissible text-center" role="alert" >
      <%= warning %>
    </div>
  <% end %>
</div>

app/views/layouts/_nav.html.erb
<header class="p-3 mb-3 border-bottom">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <%= link_to "Q&A", root_path, class:"me-5 d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none" %>
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><%= link_to "Comenzar juego", games_path, class:"nav-link px-2 link-dark" %></li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <%= link_to "Ver ranking", games_ranking_manejo_path, class:"nav-link dropdown-toggle", data: {'bs-toggle':'dropdown'}, aria: {expanded: 'false'} %>
            <ul class="dropdown-menu">
            <li><%= link_to "Ranking manejo", games_ranking_manejo_path, class:"dropdown-item" %></li>
              <li><%= link_to "Ranking petroleo", games_ranking_petroleo_path, class:"dropdown-item" %></li>
            </ul>
          </li>
          <li><%= link_to "Ver ranking", games_ranking_manejo_path, class:"nav-link px-2 link-dark" %></li>
          <li><%= link_to "Preguntas", questions_path, class:"nav-link px-2 link-dark"%></li>
          <li><%= link_to "Categorias", categories_path, class:"nav-link px-2 link-dark"%></li>
          <% if current_user.admin %>
            <li><%= link_to "Usuarios", users_path, class:"nav-link px-2 link-dark"%></li>
          <% end %>
        <% end %>
      </ul>
      <% if logged_in? %>
      <div class="dropdown text-end">
        <%= link_to "#", class: "d-block link-dark text-decoration-none dropdown-toggle", data: {"bs-toggle": "dropdown"}, aria: { expanded: "false"} do %>
          <% if current_user.avatar.attached? %>
            <%= image_tag(current_user.avatar, size: "32X32", alt: "user image", class:"rounded-circle") %>
          <% else %>
            <%= image_tag('user.png', size: "32X32", alt: "user image", class:"rounded-circle") %>
          <% end %>
        <%end%>
        <ul class="dropdown-menu text-small" style="">
          <li><%= link_to "Cerrar sesion", session_path(current_user.id), data:{ turbo_method: :delete}, class:"dropdown-item" %></li>
        </ul>
      </div>
      <%else%>
        <div class="col-md-3 text-end">
          <%= link_to "Iniciar sesion", new_session_path, class:"btn btn-outline-primary me-2" %>
        </div>
      <%end%>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Q&A</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render  partial: "layouts/nav"%>
    <div class="container">
      <%= render partial: "layouts/flash", locals: { time_alert: @time_alert, effect_alert: @effect_alert } %>
      <%= yield %>
    </div>
  </body>
</html>